CLASSPATH = xerces.jar;xalan.jar
JAVA = java
INPUT = readme.xml
CLASS = org.apache.xalan.xslt.Process

all: html text php


html: $(INPUT) html.xsl
	$(JAVA) -classpath $(CLASSPATH) $(CLASS) -IN $(INPUT) -XSL html.xsl -OUT docs.html

text: $(INPUT) text.xsl
	$(JAVA) -classpath $(CLASSPATH) $(CLASS) -IN $(INPUT) -XSL text.xsl -OUT readme.txt

php: $(INPUT) php.xsl
	$(JAVA) -classpath $(CLASSPATH) $(CLASS) -IN $(INPUT) -XSL php.xsl -OUT docs.dat
