.\" -*- nroff -*-
.TH ucc 1 2002-03-24 Exult

.SH NAME
ucc \- UseCode Compiler for Exult

.SH SYNOPSIS
.B ucc
.RI [ FILE ]

.SH DESCRIPTION
Games supported by Exult (\fIUltima 7\fR, for example) consist in
large part of Usecode.
.BR exult (1)
basically implements a virtual machine the machine language of which
is Usecode.

.B ucc
is a compiler that targets this machine language.

.SH AUTHOR
This manpage was written by Robert Bihlmeyer. It may be freely
redistributed and modified under the terms of the GNU General Public
License version 2 or higher.

.SH SEE ALSO
.BR exult (6)
