EXEC=Exult.exe
EXEEXT=

!include ../Makefile.common

MSVC_EXULT_FLX = ../data/exult.flx ../data/exult_flx.h

MSVC_EXULT_BG_FLX = ../data/exult_bg.flx ../data/exult_bg_flx.h

MSVC_EXULT_SI_FLX = ../data/exult_si.flx ../data/exult_si_flx.h 

$(MSVC_EXULT_FLX): $(OutDir)\expack.exe $(EXULT_FLX_OBJECTS:data/=../data/)
	$(OutDir)\expack -i ../data/flx.in

$(MSVC_EXULT_BG_FLX): $(OutDir)\expack.exe $(EXULT_BG_FLX_OBJECTS:data/=../data/)
	$(OutDir)\expack -i ../data/bg/flx.in

$(MSVC_EXULT_SI_FLX): $(OutDir)\expack.exe $(EXULT_SI_FLX_OBJECTS:data/=../data/)
	$(OutDir)\expack -i ../data/si/flx.in


# Exult.flx
build_ex : $(MSVC_EXULT_FLX)

install_ex : $(MSVC_EXULT_FLX)
	copy data\exult.flx "$(EXULT_INSTALL_PATH)\data"
	
clean_ex :
	del $(MSVC_EXULT_FLX:/=\)

rebuild_ex : clean_ex build_ex

reinstall_ex : clean_exe install_ex


# exult_bg.flx
build_bg : $(MSVC_EXULT_BG_FLX)

install_bg : $(MSVC_EXULT_BG_FLX)
	copy data\exult_bg.flx "$(EXULT_INSTALL_PATH)\data"
	
clean_bg :
	del $(MSVC_EXULT_BG_FLX:/=\)

rebuild_bg : clean_bg build_bg

reinstall_bg : clean_bg install_bg


# exult_si.flx
build_si : $(MSVC_EXULT_SI_FLX)

install_si : $(MSVC_EXULT_SI_FLX)
	copy data\exult_si.flx "$(EXULT_INSTALL_PATH)\data"

clean_si :
	del $(MSVC_EXULT_SI_FLX:/=\)

rebuild_si : clean_si build_si

reinst_si : clean_si install_si


