<?xml version="1.0"?> 
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns="http://www.w3.org/1999/xhtml">

<xsl:output method="xml"
	doctype-public="-//W3C//DTD XHTML 1.0 Transitional//EN"
	doctype-system="DTD/xhtml1-transitional.dtd"
	indent="yes"/>

<!-- Keys -->
<xsl:key name="faq_ref" match="faq" use="@name"/>
<xsl:key name="section_ref" match="section" use="@title"/>


<!-- Templates -->
<xsl:template match="faqs">
	<html>
	<xsl:comment>This file is automatically generated. Do not edit!</xsl:comment>
	<head>
		<title><xsl:value-of select="@title"/> FAQ</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	</head>
	<body bgcolor="#cccccc" text="#333366" link="#666699" vlink="#669966" alink="#ffcc33" background="images/back.gif">
		<div align="center">
			<table border="0" cellpadding="0" cellspacing="0" width="90%">
				<tr>
					<td align="center">
						<table border="0" cellpadding="0" cellspacing="0" width="100%">
							<tr>
								<td align="center"><img src="images/exult_logo.gif" width="181" height="127" alt="Exult Logo"/></td>
							</tr>
							<tr>
								<td><xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text></td>
							</tr>
							<tr>
								<td align="center"><font size="+1"><a href="index.shtml">Home</a> | <a href="download.shtml">Download</a> | <a href="faq.shtml">FAQ</a> | <a href="screenshots.shtml">Screen Shots</a> | <a href="dev.shtml">Development</a> | <a href="about.shtml">About Us</a> | <a href="history.shtml">History</a> | <a href="links.shtml">Links</a></font></td>
							</tr>
							<tr>
								<td><xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td>
						<h1><xsl:value-of select="@title"/> F.A.Q. (frequently asked questions) </h1> 
						<p>last changed: <xsl:value-of select="@changed"/></p>
						<hr/>
						<p>
							A text only version can be found <a href="http://exult.sourceforge.net/faq.txt">here</a> 
						</p>
						<br/>
				
					<!-- BEGIN TOC -->
					<xsl:for-each select="section">
						<p>
						<a href="#{generate-id(key('section_ref',@title))}">
							<xsl:number level="multiple"
										count="section"
										format="1. "/>
								<xsl:value-of select="@title"/>
						</a>
						<br/>
						<xsl:for-each select="faq">
							<a href="#{generate-id(key('faq_ref',@name))}">
								<xsl:number level="multiple"
											count="section|faq"
											format="1.1 "/>
								<xsl:apply-templates select="question"/>
							</a>
							<br/>
						</xsl:for-each>
						</p>
					</xsl:for-each>
					<!-- END TOC -->

					<!-- BEGIN CONTENT -->
					<xsl:apply-templates select="section"/>
					<!-- END CONTENT -->

					</td>
				</tr>
				<tr>
					<td><br/>
						<hr/>
					</td>
				</tr>
				<tr>
					<td>
						<table border="0" cellpadding="0" cellspacing="0" width="100%">
							<tr>
								<td align="center"><xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text></td>
							</tr>
							<tr>
								<td align="center">
									<a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=2335&amp;type=1" alt="SourceForge" height="31" width="88" border="0" /></a>
									<xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text>
									<a href="http://validator.w3.org/check/referer"><img src="http://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0!" height="31" width="88" border="0" /></a>
								</td>
							</tr>
							<tr>
								<td align="center"><xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text></td>
							</tr>
							<tr>
								<td align="center">
									<address><font size="-1">Problems with Exult or this webpage? <a href="mailto:exult-general@lists.sourceforge.net">Contact us.</a></font></address>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td align="center">
						<address><font size="-1">Last modified: <xsl:value-of select="@changed"/></font></address>
					</td>
				</tr>
				<tr>
					<td align="center">
						<div align="center">
							<xsl:comment>#exec cgi="cgi-bin/vipcounter.pl"</xsl:comment></div>
					</td>
				</tr>
			</table>
		</div>
	</body>
	</html>
</xsl:template>

<!-- FAQ Group Template -->
<xsl:template match="section">
	<hr width="100%"/>
	<table width="100%">
		<tr><th align="left">
			<a name="{generate-id()}">
				<xsl:number format="1. "/><xsl:value-of select="@title"/>
			</a>
		</th></tr>
		<xsl:apply-templates select="faq"/>
	</table>
</xsl:template>


<!-- FAQ Entry Template -->
<xsl:template match="faq">
	<xsl:variable name = "num_idx">
		<xsl:number level="multiple"
					count="section|faq"
					format="1.1 "/>
	</xsl:variable> 
	<tr><td><xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text></td></tr>
	<tr><td><strong>
		<a name="{generate-id()}">
			<xsl:value-of select="$num_idx"/>
			<xsl:apply-templates select="question"/>
		</a>
	</strong></td></tr>
	<tr><td><xsl:apply-templates select="answer"/></td></tr>
</xsl:template>


<xsl:template match="question">
	<xsl:apply-templates/>
</xsl:template>


<xsl:template match="answer">
	<xsl:apply-templates/>
</xsl:template>


<!-- Internal Link Template -->
<xsl:template match="ref">
	<a href="#{generate-id(key('faq_ref',@target))}">
	<xsl:choose>
		<xsl:when test="count(child::node())>0">
				<xsl:value-of select="."/>
		</xsl:when>
		<xsl:otherwise>
			<xsl:value-of select="count(key('faq_ref',@target)/parent::section/preceding-sibling::section)+1"/>
			<xsl:text>.</xsl:text>
			<xsl:value-of select="count(key('faq_ref',@target)/preceding-sibling::faq)+1"/>
		</xsl:otherwise>
	</xsl:choose>
	</a>
</xsl:template>

<!-- External Link Template -->
<xsl:template match="extref">
	<a href="{@target}">
	<xsl:choose>
		<xsl:when test="count(child::node())>0">
				<xsl:value-of select="."/>
		</xsl:when>
		<xsl:otherwise>
			<xsl:value-of select="@target"/>
		</xsl:otherwise>
	</xsl:choose>
	</a>
</xsl:template>


<!-- Misc Templates -->
<xsl:template match="Exult">
	<em>Exult</em>
</xsl:template>


<xsl:template match="cite">
		<p>
		<xsl:value-of select="@name"/>:<br/>
		<cite><xsl:value-of select="."/></cite>
		</p>
</xsl:template>


<xsl:template match="para">
	<p><xsl:apply-templates/></p>
</xsl:template>

<xsl:template match="key">
	'<font color="maroon"><xsl:value-of select="."/></font>'
</xsl:template>


<xsl:template match="kbd">
	<font color="maroon"><kbd><xsl:value-of select="."/></kbd></font>
</xsl:template>


<!-- ...................ol|dl|ul + em............... -->
<xsl:template match="ul|ol|li|strong|q|br">
  <xsl:copy>
    <xsl:apply-templates select="@*|node()"/>
  </xsl:copy>
</xsl:template>

<xsl:template match="em">
	<b><i><xsl:apply-templates/></i></b>
</xsl:template>

<!-- Key Command Templates -->
<xsl:template match="keytable">
	<table border="0" cellpadding="0" cellspacing="2" width="80%">
		<tr>
			<th colspan="3" align="left">
				<xsl:value-of select="@title"/>
			</th>
		</tr>
		<xsl:apply-templates select="keydesc"/>
	</table>
</xsl:template>


<xsl:template match="keydesc">
	<tr>
		<td nowrap="nowrap" valign="top">
			<font color="maroon"><xsl:value-of select="@name"/></font>
		</td>
		<td width="10"><xsl:text disable-output-escaping="yes">&amp;nbsp;</xsl:text></td>
		<td><xsl:value-of select="."/></td>
	</tr>
</xsl:template>


<!-- Config Table Templates -->
<xsl:template match="configdesc">
	<table border="0" cellpadding="0" cellspacing="0">
		<xsl:apply-templates select="line"/>
	</table>
</xsl:template>


<xsl:template match="line">
	<tr>
	<xsl:choose>
		<xsl:when test="count(child::comment)>0">
			<td width="150">
				<xsl:value-of select="text()"/>
			</td>
			<xsl:apply-templates select="comment"/>
		</xsl:when>
		<xsl:otherwise>
			<td colspan="2"><xsl:value-of select="."/></td>
		</xsl:otherwise>
	</xsl:choose>
	</tr>
</xsl:template>


<xsl:template match="comment">
	<td rowspan="2"><xsl:apply-templates/></td>
</xsl:template>

</xsl:stylesheet>
